### ISSUE TITLE
Issue about the dataset MVSA_M.dt file

### ISSUE THREAD

**Issue by Wnhere** [PhenoixYANG/TOM#1]
Thank you for your work!
I want to run your code on MVSA dataset, I download your .dt file. But something wrong happened.

```
File "/root/autodl-tmp/project/TOM/src/dataset.py", line 72, in __getitem__
  ids=torch.tensor(self.ids[index])
AttributeError: 'Model_Dataset' object has no attribute 'ids'
```

**Comment by PhenoixYANG** [comment]
Hello, it seems that the .dt file causes the problem. We have re-uploaded a new version and please re-download the file to run the code.

**Comment by Wnhere** [comment]
Thank you for your reply. There still seems to be an issue when I load the data.
```
File "/root/autodl-tmp/project/TOM/src/models.py", line 176, in test_step
  x,y,_id=batch
ValueError: too many values to unpack (expected 3)
```

**Comment by PhenoixYANG** [comment]
Hello, we have run the code using the updated "dt" file and did not encounter the same issue. This problem may have been caused by a delay in the update of our data on Google Drive yesterday. Please download the "test.dt" file again. If the same issue persists, please contact us again.

**Comment by Wnhere** [comment]
The same issue still persists. Could you please provide the original JSON file of the MVSA dataset? Additionally, the JSON file of your RU-Senti dataset worked perfectly. Great work on that!
```
File "/root/autodl-tmp/project/TOM/src/models.py", line 176, in test_step
  x,y,_id=batch
ValueError: too many values to unpack (expected 3)
```

**Comment by PhenoixYANG** [comment]
No problem, I will mail you with the json files soon. Please let me know your email address.

**Comment by Wnhere** [comment]
Thanks a lot! Here is my email address:
```
toashin9@gmail.com

**Comment by Sane-219** [comment]
Hello, could you also send me the original JSON file of MVSA dataset? My email is zhiyansu594@gmail.com. Thanks!

> No problem, I will mail you with the json files soon. Please let me know your email address.

**Comment by PhenoixYANG** [comment]
> Hello, could you also send me the original JSON file of MVSA dataset? My email is [zhiyansu594@gmail.com](mailto:zhiyansu594@gmail.com). Thanks!
> 
> >We have sent the files, please check your email.
